name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      REPO_URL: https://github.com/MindPatch/hacking-lab/
      SONAR_PROJECTKEY: gradle-finish
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull Blacklock Code Scanner Docker Image
        run: docker pull blacklocksec/code-scanner:latest

      - name: Run Blacklock Code Scanner
        run: |
          docker run --rm -v $(pwd):/app \
            -e SONAR_PROJECTKEY='gradle-finish' \
            -e SONAR_HOST_URL="https://sonar.blacklock.io" \
            -e SONAR_TOKEN="sqp_c60d18a8d488c458ef06165a2ff19aec18d5b7df" \
            blacklocksec/code-scanner:latest

      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
